// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbx1BHMErdm6IWxm9C3IJ1BaAyTv01ys',
    appId: '1:32305859093:web:f21e4416f18b938ca6dc1c',
    messagingSenderId: '32305859093',
    projectId: 'pet-app-f5500',
    authDomain: 'pet-app-f5500.firebaseapp.com',
    storageBucket: 'pet-app-f5500.appspot.com',
    measurementId: 'G-7S4012MME9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDz4Rys0OV00VXBIoMugvABdLdh9YhxR0',
    appId: '1:32305859093:android:2441ed89955949a5a6dc1c',
    messagingSenderId: '32305859093',
    projectId: 'pet-app-f5500',
    storageBucket: 'pet-app-f5500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWbI-5j31Ri5pemWS-pesMjpSYracZj0',
    appId: '1:32305859093:ios:9bdd1bffbe6cef15a6dc1c',
    messagingSenderId: '32305859093',
    projectId: 'pet-app-f5500',
    storageBucket: 'pet-app-f5500.appspot.com',
    iosClientId: '32305859093-4buufpdl8g5tugnbnigkhbmb08nqeooa.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapp',
  );
}
